version: '3.9'

services:
  ui:
    container_name: 'myapp'
    image: 'myapp'
    build:
      context: .
      dockerfile: Dockerfilenginx
    ports:
      - "80:80"
    depends_on:
      - "keycloak"
  keycloak:
    container_name: keycloak
    image: keycloak
    build:
      context: .
      dockerfile: Dockerfilekeycloak
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KK_TO_RMQ_URL: rabbitmq
        KK_TO_RMQ_PORT: 5672
        KK_TO_RMQ_VHOST: '/'
        KK_TO_RMQ_EXCHANGE: amq.topic
        KK_TO_RMQ_USERNAME: guest
        KK_TO_RMQ_PASSWORD: guest
        KK_TO_RMQ_USE_TLS: false
    volumes:
      - .\keycloack_config:/config
    ports:
      - "8080:8080"
    command: start-dev

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - keycloak




